// ----------------------------------------------------------------------------
// Cloudflare R2 service
//
// R2 speaks the S3 API, so we use @aws-sdk/client-s3 pointed at the R2
// endpoint. Two upload patterns are supported and the controller layer
// picks which to expose:
//
//   1. Server-side upload   — client streams a file to the API, API streams
//                              it to R2 via uploadObject().
//   2. Presigned PUT URL    — client asks the API for a short-lived URL via
//                              getPresignedUploadUrl(), then PUTs directly
//                              to R2 (saves a hop through our server).
//
// Public read URLs are built from R2_PUBLIC_BASE_URL (a custom domain or
// the r2.dev subdomain), not generated by signing.
// ----------------------------------------------------------------------------

import {
  DeleteObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';

import { config } from '../config/env.js';
import { logger } from '../utils/logger.js';

// R2 returns auth errors if region is omitted; 'auto' is the documented value.
const R2_REGION = 'auto';

let cachedClient = null;

function assertConfigured() {
  const missing = [];
  if (!config.R2_ACCOUNT_ID) missing.push('R2_ACCOUNT_ID');
  if (!config.R2_ACCESS_KEY_ID) missing.push('R2_ACCESS_KEY_ID');
  if (!config.R2_SECRET_ACCESS_KEY) missing.push('R2_SECRET_ACCESS_KEY');
  if (!config.R2_BUCKET) missing.push('R2_BUCKET');
  if (missing.length > 0) {
    throw new Error(
      `R2 is not configured. Missing env vars: ${missing.join(', ')}`
    );
  }
}

export function getR2Client() {
  if (cachedClient) return cachedClient;
  assertConfigured();
  cachedClient = new S3Client({
    credentials: {
      accessKeyId: config.R2_ACCESS_KEY_ID,
      secretAccessKey: config.R2_SECRET_ACCESS_KEY,
    },
    endpoint: `https://${config.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
    region: R2_REGION,
  });
  return cachedClient;
}

// Build the publicly accessible URL for an object. Requires
// R2_PUBLIC_BASE_URL — the bucket's custom domain (preferred) or r2.dev URL.
export function buildPublicUrl(key) {
  if (!config.R2_PUBLIC_BASE_URL) {
    throw new Error(
      'R2_PUBLIC_BASE_URL is not set — cannot build public URL for R2 object'
    );
  }
  const base = config.R2_PUBLIC_BASE_URL.replace(/\/+$/, '');
  const cleanKey = key.replace(/^\/+/, '');
  return `${base}/${cleanKey}`;
}

// Strip R2_PUBLIC_BASE_URL off a stored URL to recover the object key.
// Used as a fallback for legacy media records that pre-date the r2_key field.
// Returns null if the URL doesn't live under our bucket's public base.
export function keyFromPublicUrl(url) {
  if (!url || !config.R2_PUBLIC_BASE_URL) return null;
  const base = config.R2_PUBLIC_BASE_URL.replace(/\/+$/, '');
  if (!url.startsWith(base + '/')) return null;
  return url.slice(base.length + 1);
}

// Server-side upload. Body can be a Buffer, Uint8Array, or stream.
export async function uploadObject({
  body,
  cacheControl,
  contentType,
  key,
  metadata,
}) {
  assertConfigured();
  const client = getR2Client();

  await client.send(
    new PutObjectCommand({
      Body: body,
      Bucket: config.R2_BUCKET,
      CacheControl: cacheControl,
      ContentType: contentType,
      Key: key,
      Metadata: metadata,
    })
  );

  logger.info('R2 object uploaded', {
    bucket: config.R2_BUCKET,
    contentType,
    key,
  });

  return {
    bucket: config.R2_BUCKET,
    key,
    url: config.R2_PUBLIC_BASE_URL ? buildPublicUrl(key) : null,
  };
}

// Presigned PUT URL — client uploads directly to R2 with this URL.
// expiresIn is seconds; default 5 min is enough for a single upload.
export async function getPresignedUploadUrl({
  contentType,
  expiresIn = 300,
  key,
}) {
  assertConfigured();
  const client = getR2Client();

  const command = new PutObjectCommand({
    Bucket: config.R2_BUCKET,
    ContentType: contentType,
    Key: key,
  });

  const uploadUrl = await getSignedUrl(client, command, { expiresIn });

  return {
    bucket: config.R2_BUCKET,
    expiresIn,
    key,
    publicUrl: config.R2_PUBLIC_BASE_URL ? buildPublicUrl(key) : null,
    uploadUrl,
  };
}

// Presigned GET URL — for serving private objects without making the bucket
// public. Only needed if you keep objects private; public-read buckets just
// use buildPublicUrl().
export async function getPresignedDownloadUrl({ expiresIn = 300, key }) {
  assertConfigured();
  const client = getR2Client();

  const command = new GetObjectCommand({
    Bucket: config.R2_BUCKET,
    Key: key,
  });

  return getSignedUrl(client, command, { expiresIn });
}

export async function deleteObject(key) {
  assertConfigured();
  const client = getR2Client();

  await client.send(
    new DeleteObjectCommand({
      Bucket: config.R2_BUCKET,
      Key: key,
    })
  );

  logger.info('R2 object deleted', { bucket: config.R2_BUCKET, key });
}

// Returns true if the object exists, false on 404. Anything else throws.
export async function objectExists(key) {
  assertConfigured();
  const client = getR2Client();

  try {
    await client.send(
      new HeadObjectCommand({ Bucket: config.R2_BUCKET, Key: key })
    );
    return true;
  } catch (error) {
    if (
      error?.$metadata?.httpStatusCode === 404 ||
      error?.name === 'NotFound'
    ) {
      return false;
    }
    throw error;
  }
}
